# Generated by Django 4.1.7 on 2023-04-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_categoty"),
    ]

    operations = [
        migrations.RenameModel(old_name="Categoty", new_name="Category",),
    ]
