# Generated by Django 4.1.7 on 2023-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_product_count_product_description_product_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=255),
        ),
    ]
